### ISSUE TITLE
Error when installing from Package Control

### ISSUE THREAD

**Issue by aeronavery** [ziglang/sublime-zig-language#34]
This error pops up when installing the package from Package Control:

`error loading meta info from Packages/Zig Language/Preferences/Comments.tmPreferences: Error parsing plist xml: expected < in file Packages/Zig Language/Preferences/Comments.tmPreferences on line: 1`

It only pops up when you first install the package. Once you install it and manually select Syntax -> Zig the package works like expected without error. Looks like this error was introduced when making this package compatible with TextMate.

**Comment by emekoi** [comment]
as for this issue i'm not familiar with TextMate so i don't if there is a way to solve this, while maintaining compatibility with TextMate. do you know anything about this @aequitas?

**Comment by aequitas** [comment]
I'll dive into this.

**Comment by aequitas** [comment]
My guess is this is because the file in `Preferences` is a symlink instead of a real file. I changed this in https://github.com/ziglang/sublime-zig-language/pull/37. But I couldn't find a quick way of testing this with Package control, so I can't confirm. If this doesn't fix it feel free to yank the Textmate specific stuff from the package and I'll maintain a separate repository for a Textmate compatible version.

**Comment by emekoi** [comment]
would it be viable to just copy the file?

**Comment by aequitas** [comment]
Yes, see #37
