### ISSUE TITLE
set "quiet: true" to zig fmt build script

### ISSUE THREAD

**Issue by anosovic** [ziglang/sublime-zig-language#36]
if format on save is on, then zig fmt will run. when it does, "[Finished in 0.4s]" will pop up at the bottom.

the formatter shouldnt need to pop open a console window on every save. setting "quiet: true" in the .sublime-build script for zig fmt fixes this.

**Comment by emekoi** [comment]
adding the quiet flag still causes an empty panel to show but `"show_panel_on_build": false` in your sublime settings will hide the panel by deafult. i can also add `view.window().run_command("hide_panel")` to automatically hide the panel, but i don't know if other users will like that.

**Comment by anosovic** [comment]
ah, didn't realize that--this is the default functionality of the package

thanks for the tip and modification

**Comment by emekoi** [comment]
np, i just pushed a new release with the option to autohide the panel if you set `zig.quiet` to `true`.

**Comment by travisstaloch** [comment]
I figured out that I needed to add a `~/.config/sublime-text/Packages/User/Zig.sublime-settings` file in order to add the `"zig.quiet": true` option.  And after doing this, the bottom panel does not pop up anymore after saving/fmt.  This is good.  

However now the panel never pops up, even when there are build errors. 

@emekoi I propose to make this flag only apply when the command is 'fmt'.  Does this sound reasonable?  If so, is it possible?  I'm looking at [Zig.py](https://github.com/ziglang/sublime-zig-language/blob/master/Zig.py#L380) and not sure how to check if the command is a fmt.  Any ideas?  I would gladly make a pr if I could figure out how to do this.

Also, if we can do this, I suggest making zig.quiet default to true to avoid this annoying panel popup on every save.

**Comment by travisstaloch** [comment]
I'm sure I missed something @emekoi .  It looks like [your commit](https://github.com/ziglang/sublime-zig-language/commit/e8f68cdf3874b6735282c669793204167b58392e) to address this sets `"quiet": true` for the fmt commands. Any idea why would this not have been happening for me (before adding the `"zig.quiet": true` setting)?
